### ISSUE TITLE
Undeclared global variable "table_contains" at tables/table_contains.lua:13

### ISSUE THREAD

**Issue by Bastrabun** [sbrl/Minetest-WorldEditAdditions#67] opened 2021-07-15 15:52 UTC
2021-07-15 17:51:00: WARNING[Main]: Undeclared global variable "table_contains" accessed at ...tions/worldeditadditions/utils/tables/table_contains.lua:13

**Comment by sbrl** [comment] 2021-07-18 00:27
Hey there, @Bastrabun! Thanks for the report. I need some more info to debug this.

 - What version of WorldEditAdditions are you using, and how did you install it?
 - Does this still happen if you check out the latest version from the `main` branch of this Git repository?
 - Can you include some reproduction steps?
 - What version of Minetest are you using? If you're comfortable with the command line, the output of `minetest --version` would  be really helpful.

Many thanks :-)

**Comment by Bastrabun** [comment] 2021-07-18 05:40
Happened with 442cb8a8d84e611df95d85ffd9b45d379222a984 and installed via git pull

Doesn't happen in the latest main 496d41731a1efc30bdb033bfead28324822fa1ac

Now this happens: 

2021-07-18 07:37:26: WARNING[Main]: Undeclared global variable "bit" accessed at ...test-WorldEditAdditions/worldeditadditions/utils/bit.lua:15

Repro: Have Worldeditaddtions enabled in world.mt and start the server. It happens during the startup sequence.

Minetest version 5.4.1 in all cases

Woah, there's a lot happening lately in this mod, maybe I wait until you're done before reporting small-scale issues like this :D

**Comment by VorTechnix** [comment] 2021-07-18 18:25
~~Wow a bug report from someone other than me!~~

> 2021-07-18 07:37:26: WARNING[Main]: Undeclared global variable "bit" accessed at ...test-WorldEditAdditions/worldeditadditions/utils/bit.lua:15

This is a strange report because `WorldEditAdditions/worldeditadditions/utils/bit.lua` doesn't exist (at least since the last release).

![image](https://user-images.githubusercontent.com/45538536/126077997-147c5571-b58e-408a-a656-140791dbd02a.png)

It goes from `axes.lua` to `lru_benchmark.lua` so this is very mysterious.

Also for reproducing did you mean "Have `load_mod_worldeditadditions = true` in world.mt and start the server."?

Lastly have you tried deleting your local repository and re-cloning main? It could be there's a bad delta causing ghost code.

**Comment by sbrl** [comment] 2021-07-18 19:08
> Doesn't happen in the latest main 496d417

Glad to hear it! I thought I'd fixed that one.

> 2021-07-18 07:37:26: WARNING[Main]: Undeclared global variable "bit" accessed at ...test-WorldEditAdditions/worldeditadditions/utils/bit.lua:15

> This is a strange report because WorldEditAdditions/worldeditadditions/utils/bit.lua doesn't exist (at least since the last release).

`WorldEditAdditions/worldeditadditions/utils/bit.lua` does exist in the latest `main` - I added it yesterday to centralise the bitwise operation polyfills that WorldEditAdditions uses. You can safely ignore that error @Bastrabun -- it shouldn't do any harm. WorldEditAdditions checks to see if the `bit` global already exists you see before loading the polyfill.

I'll look at fixing it though to avoid the warning in peoples' logs :-)

I think we can close this issue now.

**Closed** 2021-07-18 19:17 UTC
Labels: infoneeded
